### ISSUE TITLE
Request to answer questions

### ISSUE THREAD

**Issue by happycaoyue** [IIGROUP/RADN#1]
In test_val.py, the pre-trained model is "WResNet-lr=0.0001-bs=2-10". However, your released pre-trained in google drive is "WResNet-lr=0.0001-bs=2". What's the difference between these two pre-trained models.

**Comment by happycaoyue** [comment]
I test the ntire validation to use the "WResNet-lr=0.0001-bs=2", the result is 0.8233 (PLCC) | 0.8284 (SROCC). Can you check it?

**Comment by EzioBy** [comment]
> In test_val.py, the pre-trained model is "WResNet-lr=0.0001-bs=2-10". However, your released pre-trained in google drive is "WResNet-lr=0.0001-bs=2". What's the difference between these two pre-trained models.

Hi, '-10' just means we use the 10th fold as the validation dataset. It is kind of ambiguous so I finally removed the characters.

**Comment by EzioBy** [comment]
> I test the ntire validation to use the "WResNet-lr=0.0001-bs=2", the result is 0.8233 (PLCC) | 0.8284 (SROCC). Can you check it?

Hi happycaoyue, this result is almost correct. Please note that the performance on the challenge leaderboard  is obtained by ensembling.
