### ISSUE TITLE
关于model.RADN

### ISSUE THREAD

**Issue by Oraclexu** [IIGROUP/RADN#2]
代码中没有RADN网络，只有WResNet，是还没上传嘛，还是就是用WResNet作为网络
感谢作者的贡献！

**Comment by EzioBy** [comment]
Hi Oraclexu！
WResNet是我们的baseline，RADN是论文的核心模型，
RADN部分的代码还在refine中，会尽快release，感谢关注！
----------------------------------------------------------------
Hi Oraclexu!
WResNet is our baseline and RADN is the core model in the paper,
The codes of the RADN are still being refined and will be released as soon as possible. Thanks for your attention!

**Comment by weihaox** [comment]
The code of RADN has been released. Please check.
