### ISSUE TITLE
重新训练的时候发现RADN的结果都是nan，请问是什么原因？

### ISSUE THREAD

**Issue by lllllllllllll-llll** [IIGROUP/RADN#5]
用RADN进行训练测试的结果如下：
Validation Results - Epoch: 6 SROCC: nan KROCC: nan PLCC: nan RMSE: 119.7862 MAE: 93.5760 OR: 0.00%
而用WResNet的结果就在0.75左右，是不是RADN代码有问题？

**Comment by Shuweis** [comment]
non-local和deformable模块都比较难训练，会有不稳定因素，因此我们采用了分步训练的方式，先训WResNet再将训练好的权重加载到RADN中去训练整体的网络，按照这种策略几乎就不会出现问题了。
