### ISSUE TITLE
请问能不能开放预训练的代码呢？

### ISSUE THREAD

**Issue by lllllllllllll-llll** [IIGROUP/RADN#8]
我用作者提供的代码跑，在0序列上结果始终到不了0.750，那一定是没有加载预训练model的问题，能不能提供预训练代码呢？
因为如果不加载预训练model只能跑到0.730，那么是不是说明此网络本身的效果提升就不大，而是借助于预训练的model才达到很好的效果呢？

**Comment by Shuweis** [comment]
请问您提到的0序列指的是？

**Comment by lllllllllllll-llll** [comment]
> 请问您提到的0序列指的是？

就是训练代码应该是在训练集上随机划分了1000此不同的序列吧，李鼎全的代码里面在设置的时候用exp_id来表示的，默认是0。我训练release的代码的时候就是用的exp_id为0的序列看结果的。
谢谢回复

**Comment by Shuweis** [comment]
你是说WResNet无法跑到0.75吗？

**Comment by lllllllllllll-llll** [comment]
可能是系统不同的原因吧，我用的是win10环境，WResNet在exp_id=0的情况下结果在0.73多，但是把0.73的成绩提交到NTRIE挑战赛的validation结果上是0.7左右，应该说是验证集的结果会比我训练的结果低0.03。但是我看到挑战赛页面上RADN的结果是0.87，那么如何在训练集上跑到这么高的效果呢？
谢谢

**Comment by Shuweis** [comment]
1.我们所有实验都是在linux环境下进行的
2.不同版本的pytorch等包跑出来的结果会有所不同，我们建议使用torch1.7以上的版本
3.页面上的结果不是RADN的结果是我们ensemble之后的最好成绩
4.RADN的结果在论文的abalation study中
